### ISSUE TITLE
modifying script to pull CurrentTemperature

### ISSUE THREAD

**Issue by JangoBritt** [NovaGL/homebridge-http-advanced#1]
@NovaGL I qas looking at the code in index.js, as I've been looking for a branch that could be modified to pull temperature from an HTTP device, and this is so far the closest I've come.

If I were to branch, and duplicate the "getBrightness" function (line 234) into a getCurrentTemperature function, this is probably where I'd parse out the temperature from my HTTP string.

on Line 248, you have the function `var level = parseInt(responseBody);` does that responseBody expect a response of only a value of the lighting percentage?

How could I change this to parse a larger response, and find a line with a substring?

I'm not particularly familiar with the language, unfortunately :(

**Comment by JangoBritt** [comment]
to remind, the HTTP response is this:

> motion_detected_1=off
> mdv1=0
> pir=off
> gp_input_0=off
> gp_input_1=off
> gp_input_2=off
> gp_input_3=off
> storage_full_sd=off
> storage_failure_sd=off
> in_recording=off
> audio_detected=off
> gp_output_0=off
> gp_output_1=off
> gp_output_2=off
> gp_output_3=off
> pan_pos=0.000000
> tilt_pos=0.000000
> zoom_mag=0.000000
> focus_step=0
> irled=off
> playing_music=off
> music_repeated=off
> night_led=off
> camera_name=<redacted>
> speaker_occupied=off
> mic_muted=off
> td=normal
> 
> tdC=23
> tdF=73
> 
> tdC=23
> tdF=73

I'm only interested in the tdC=23

**Comment by NovaGL** [comment]
The responses only allow the actual output meaning, it would only allow 23.

You need to find a way externally to get it to display 23.

Eg you could do your curl output in php and link the php file to homebridge.

Alternatively you could create your own homebridge plugin that allows curl but that gets very complicated.

**Comment by JangoBritt** [comment]
how about this, since the settings strings are static:

```

String lines[] = responseBody.split("\\r?\\n");
var level = parseInt(Lines[29])
```

**Comment by NovaGL** [comment]
So this is what I have so far. will need to integrate it and maybe do a branch for you or you can fork it.

You can experiment with the below as it's a standalone node project.

```
var request = require("request");
var URL = "http://192.168.1.4/eng/web_event.cgi";

request(URL, function (error, response, body) {
        if (!error && response.statusCode == 200) {
            var re = /tdC=(\d*)/g ;
            var result = re.exec(body);
            console.log(result[1])                 
            }
    }
);
```

**Comment by NovaGL** [comment]
This has now been added and can be found in the MyDLink branch.

Please see the below commit for what was changed, there is also an example config file.
d78754fa621435ad244661ca918d6e6f32907e89

Please let me know how you go and close the issue if it is resolved.

**Comment by JangoBritt** [comment]
@NovaGL 

Hey, this is really kind of you, thanks.

I cloned the repo, and replaced the index.js with the updated one from the branch, and then added the below section to my config.json

```
    ],
    "accessories": [
        {
             "accessory": "Http",
             "name": "Temperature Sensor",
             "temp_url": "http://192.168.1.4/eng/web_event.cgi",
             "service": "Temperature",
             "username": "admin",
             "password": "[removed]"
        }
    ]

```

The error I'm getting when loading homebridge is this:

```

/usr/local/lib/node_modules/homebridge/lib/server.js:359
  if (!(services[0] instanceof Service)) {
                ^

TypeError: Cannot read property '0' of undefined
    at Server._createAccessory (/usr/local/lib/node_modules/homebridge/lib/server.js:359:17)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:245:26)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:72:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

```

It's quite possible that I've forgotten to mention an important catch in the CGI script, that means that the page is constantly loading, and tdC and tdF keep adding, and adding and adding to the page.

In my curl string, I was able to do a timeout on the curl command: `curl -u admin:[removed] -m 1 http://192.168.1.4/eng/web_event.cgi | grep 'tdC=' | sed -n -e 's/^tdC=//p'` so that it stopped the curl after a timeout of 1 second

**Comment by NovaGL** [comment]
It's really hard for me to help without access to the source.

You have two solutions.
1. Create another page eg PHP which does the curl for you. Make sure it only displays the tdC.
   OR
2. Look at my simple request node project above. Modify that until you get the right output in console log. Make sure you have request installed in the node_modules sub folder for the example to work.

It is possible that my project is missing something and the data isn't being passed which makes it undefined. Good luck and hope it works for you.

**Comment by JangoBritt** [comment]
I will give all that a go. Thanks for your help, and time @NovaGL
